# -*- coding: utf-8 -*-
"""PruebaTecnica_Melisa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13IahgShaPGUAdW14gN1_55Bn7bgjrnTF

# Prueba técnica - Consultor Analitico
*Laura Melisa Patarroyo Godoy*

**Problema de negocio:** Una compañía de telecomunicaciones peruana busca establecer accionables estratégicos y de negocio orientados a reducir las intenciones de cancelación de servicio y el abandono de clientes (churn). Para lo anterior, se realizó una segmentación de clientes y se identificó un clúster crítico (cluster 3) con alta propensión al churn y elevadas intenciones de cancelación.
**Objetivo**: diseñar iniciativas focalizadas para este Cluster clave (cluster3), con el fin de reducir el churn

Este análisis se centrará en entender los principales factores que impulsan el churn dentro de este clúster teniendo en cuenta las variables de segmentación de clientes y las transcripciones de llamadas de clientes

## **Roadmap Analítico**

El análisis seguirá el siguiente flujo:

*   Paso 1: Exploración de Datos. Aquí se revisaran las variables usadas para la segmentación y se identificarán patrones de comportamiento de los clientes del Clúster 3, para entender por que los hace ser tan 'críticos'.
*   Paso 2: Análisis de las transcripciones de las llamadas. Aquí se identificará las principales razones del churn, que los clientes expresan cuando realizan las llamadas con intenciones de cancelación, usando NLP.
*   Paso 3: Relacionar los hallazgos del Paso1 con los hallazgos del Paso2. Llamadas Vs Caracterización.
*   Paso 4: Diseño de Estrategias. Aquí se definirán las iniciativas de retención reactivas y proactivas, teniendo como base los resultados de los pasos anteriores.
*  Paso 5: Métricas de Impacto. Aquí se definirán KPIs para medir qué tan efectivas son las estrategias propuestas.

## **Exploración de Datos (EDA)**
"""

!pip install wordcloud
!pip install gdown

# Importación principales librerias a usar
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.feature_extraction.text import CountVectorizer
import re

## Como el archivo que contiene el dataset del cluster es tan grande. Se leerá desde la URL de Drive.
import gdown
url = "https://drive.google.com/uc?id=1S8v5VLiF_t7rrhCwwUxKkQ3WkRgJZ49-"
gdown.download(url, "ANEXO_VARIABLES_CLUSTER_3.xlsx", quiet=False)

## Lectura y creación de DF de los 2 archivos a analizar.
llamadas = pd.read_excel("https://raw.githubusercontent.com/lmelisapg/PruebaTecnica/main/datos/LLAMADAS_VF.xlsx")
cluster = pd.read_excel("ANEXO_VARIABLES_CLUSTER_3.xlsx")

## Se inicia con la exploración del DF del cluster3 de clientes.
## Tamaño del DF
cluster.shape

## Revisión de DF
cluster.head()

## Verificación de que los datos sean solo del cluster3
cluster["CLUSTER_ID"].value_counts()

pd.set_option('display.max_rows', None)

## Revisión de columnas del DF
cluster.columns

"""Revisando el significado en el Diccionario de datos de las variables que tenemos, observamos que hay variables que nos dan información del cliente en cuanto al perfil, los servicios que tiene contratados, la facturación, interacciones con soporte, las caracteristicas del servicio que tiene, aplicación de campañas e intenciones de cancelación."""

## Datos Faltantes
cluster.isnull().sum().sort_values(ascending=False).head(15)

## Las variables VAL_PENETRACION_NODO y VAL_CHURN_ZONA están en su totalidad nulas, por lo que no aportan al entendimiento ni caracterización de los clientes.
cluster = cluster.drop(columns=["VAL_PENETRACION_NODO","VAL_CHURN_ZONA"])

"""Las otras variables que tienen algunos nulos se mantendrán ya que la proporción es mínima en comparación con el tamaño total del dataset. Y algunas siguiendo la descripción del diccionario de datos, pueden ser utiles al realizar el perfilamiento de los clientes."""

pd.set_option('display.max_rows', None)

cluster.describe().T

sns.histplot(cluster["ANTIGUEDAD_MESES"], bins=50, kde=True)

## Hay valores atipicos en la antiguedad, ya que más de 600 meses serian 50 años que una empresa lleve en el mercado
cluster[cluster["ANTIGUEDAD_MESES"] > 600].shape

## La proporción es muy poca vs el total del dataset, por lo que unicamente vamos a realizar un Capping a estos valores:
cluster.loc[cluster["ANTIGUEDAD_MESES"] > 600, "ANTIGUEDAD_MESES"] = 360
cluster[cluster["ANTIGUEDAD_MESES"] > 600].shape

## Hay valores atipicos en los minutos de interrupción al servicio. No deberian haber menores a 0. Reemplazamos por 0 para evitar distorsiones en el análisis.
cluster[cluster["VAL_DOWNTIME"] < 0].shape
cluster.loc[cluster["VAL_DOWNTIME"] < 0, "VAL_DOWNTIME"] = 0

cluster[cluster["VAL_DOWNTIME"] < 0].shape

cluster["CANT_SRV_BSC"].value_counts()

## La mayoria de los clientes cuentan con al menos 4 servicios basicos contratados.

cluster["CANT_SRV_ADIC"].value_counts().head(10)
## Los cllientes del cluster poseen entre 4 y 6 servicios adicionales

cluster[["ESTRATO_1","ESTRATO_2","ESTRATO_3","ESTRATO_4","ESTRATO_5","ESTRATO_6"]].mean()*100
# La mayoria de clientes del cluster están entre estratos 2-3: clase media.

fig, axes = plt.subplots(1,2, figsize=(14,5))

sns.histplot(cluster["VAL_RENTA_ACTUAL"], bins=50, kde=True, ax=axes[0])
axes[0].set_title("Distribución de renta mensual actual")

sns.histplot(cluster["VAL_VAR_RENTA"], bins=50, ax=axes[1])
axes[1].set_title("Variación de renta en últimos 6 meses")

plt.tight_layout()
plt.show()

"""La mayoria de clientes manejan una renta entre 80.000 – 110.000. Los precios se mantienen relativamente estables, no se observan muchos cambios en la factura"""

fig, axes = plt.subplots(1, 3, figsize=(18,5))

# Reclamos
sns.histplot(cluster["VAL_RECLAMOS_MES"], bins=20, ax=axes[0])
axes[0].set_title("Distribución de reclamos mensuales")
axes[0].set_xlabel("Número de reclamos")
axes[0].set_ylabel("Clientes")

# Downtime
sns.histplot(cluster["VAL_DOWNTIME"], bins=50, ax=axes[1])
axes[1].set_title("Distribución de downtime")
axes[1].set_xlabel("Minutos de interrupción")

# Intención de cancelación
sns.countplot(x=cluster["BAN_INTENCION_CANCELACION"], ax=axes[2])
axes[2].set_title("Clientes con intención de cancelación")
axes[2].set_xlabel("Intención (0 = No, 1 = Sí)")
axes[2].set_ylabel("Clientes")

plt.tight_layout()

plt.show()

print(cluster["VAL_RECLAMOS_MES"].mean())
print((cluster["VAL_RECLAMOS_MES"] > 0).mean()*100)
## El 37% de clientes tienen al menos 1 reclamo por mes

(cluster["VAL_DOWNTIME"] > 0).mean()*100
## 12.1% de clientes experimentaron interrupciones del servicio

cluster["BAN_INTENCION_CANCELACION"].mean()*100
## Al menos un 20% de los clientes tuvieron intentos de cancelación

cluster["BAN_MORA_30"].mean()*100
## Solo el 1% presenta una mora de más de 30 días.

# Calcular la correlación numérica entre la variable de reclamos mes vs las intenciones de cancelación
correlacion = cluster['VAL_RECLAMOS_MES'].corr(cluster['BAN_INTENCION_CANCELACION'])
print(f"La correlación entre reclamos e intención de cancelación es: {correlacion:.2f}")

"""Al contrario de lo que pensaba, el resultado muestra una correlación baja entre ambas variables, por lo que la relación directa entre reclamos y cancelación no es fuerte.

Esto podría sugerir que puede existir un churn silencioso, es decir, no no todos los clientes que cancelan necesariamente presentan reclamos previos.

Por otra parte, el churn podría estar influenciado también por otros factores como percepción de valor del servicio, facturación o problemas técnicos.
"""

plt.figure(figsize=(10, 6))

# Boxplot para ver ayudar visualmente a ver la distribución
sns.boxplot(x='BAN_INTENCION_CANCELACION', y='VAL_RECLAMOS_MES', data=cluster, palette="Reds")

plt.title('Distribución de Reclamos Mensuales vs Intención de Cancelación')
plt.xlabel('¿Tiene Intención de Cancelación? (0=No, 1=Sí)')
plt.ylabel('Número de Reclamos al Mes')
plt.grid(axis='y', linestyle='--', alpha=0.7)

plt.show()

# Y de acuerdo al resultado previo, quienes más llaman con intención de cancelación, no han realizado efectivamente reclamos previamente.

cluster['RANGO_RECLAMOS'] = pd.cut(cluster['VAL_RECLAMOS_MES'], bins=[-1, 0, 1, 2, 5, 100],
                                 labels=['0', '1', '2', '3-5', 'Más de 5'])

# Calculamos el % de intención de cancelación por rango
tasa_cancelacion = cluster.groupby('RANGO_RECLAMOS')['BAN_INTENCION_CANCELACION'].mean() * 100

tasa_cancelacion.plot(kind='bar', color='skyblue', figsize=(8,5))
plt.title('% Intención de Cancelación según cantidad de reclamos')
plt.ylabel('Tasa de Intención (%)')
plt.xlabel('Cantidad de Reclamos al Mes')
plt.show()

services = ["BAN_INTERNET","BAN_TV","BAN_VOZ"]
streaming = ["BAN_NETFLIX","BAN_DISNEY","BAN_PRIME","BAN_HBO","BAN_WIN"]

services_usage = cluster[services].mean()*100
streaming_usage = cluster[streaming].mean()*100

fig, axes = plt.subplots(1, 2, figsize=(14,5))

# Triple Play
services_usage.plot(kind="bar", ax=axes[0])
axes[0].set_title("Servicios principales (Triple Play)")
axes[0].set_ylabel("Porcentaje de clientes")
axes[0].set_xlabel("Servicio")

# Streaming
streaming_usage.plot(kind="bar", ax=axes[1])
axes[1].set_title("Servicios de streaming")
axes[1].set_ylabel("Porcentaje de clientes")
axes[1].set_xlabel("Servicio")

plt.tight_layout()

plt.show()

print(cluster["BAN_INTERNET"].mean()*100)
print(cluster["BAN_TV"].mean()*100)
print(cluster["BAN_VOZ"].mean()*100)
## La mayoria de los clientes tienen los 3 servicios contratados (Triple Play), es decir son clientes con paquetes completos.

streaming = ["BAN_NETFLIX","BAN_DISNEY","BAN_PRIME","BAN_HBO","BAN_WIN"]
cluster[streaming].mean()*100

## Sin embargo, no es un cluster de mucho uso de streaming. La adquisición de plataformas es relativamente baja.

print("Antigüedad promedio de clientes:", cluster["ANTIGUEDAD_MESES"].mean(), "meses")
print("Clientes con intención de cancelación", cluster["BAN_INTENCION_CANCELACION"].mean()*100,"%")
print("Clientes con mora mayor a 30 días:", cluster["BAN_MORA_30"].mean()*100,"%")
print("Promedio de reclamos por cliente al mes:", cluster["VAL_RECLAMOS_MES"].mean())
print("Clientes que experimentaron al menos una interrupción del servicio:", (cluster["VAL_DOWNTIME"] > 0).mean()*100,"%")
print("Porcentaje de uso de servicios:", cluster[["BAN_INTERNET","BAN_TV","BAN_VOZ"]].mean()*100,"%")

"""**Perfilamiento de los clientes:**
A partir del EDA realizado, se pueden resaltar caracteristicas como:

* La antiguedad promedio de los clientes es de 80 meses, es decir aprox 6 años y medio; es decir son clientes con una relación larga con la compañia.
* La mayoria de clientes cuentan con paquetes completos de servicios y gran cantidad de servicios adicionales contratados, por lo que serian clientes de gran impacto en caso de cancelación.
* Los clientes pertenecen a una clase media, siendo los principales estratos:2 y 3.
* La renta promedio mensual está sobre los 96.000 y no se observan cambios brusco en la facturación en los ultimos meses. Frente al comportamiento de pago, vemos que muy pocos, solo el 1% tiene una mora superior a 30 dias
* Aproximadamente el 38% de los clientes presenta al menos un reclamo mensual y cerca del 12.1% de los clientes experimentó interrupciones del servicio, lo que infiere que el churn se puede deber a problemas en la experiencia del cliente y calidad del servicio.

## **Análisis Transcripción de llamadas**
"""

##Tamaño del DF
llamadas.shape

## Vista del DF
llamadas.head()

## Revisión que las llamadas pertenezcan al cluster 3
llamadas["cluster"].value_counts()

##Filtramos llamadas solo de nuestro cluster crítico:
llamadas_cluster3 = llamadas[llamadas["cluster"] == 3].copy()

llamadas_cluster3.shape

## Limpieza básica del texto

def clean_text(text):
    text = str(text).lower()                ## Convertimos todo a minuscula
    text = re.sub(r'\d+', ' ', text)        ## Quitamos numeros
    text = re.sub(r'[^\w\s]', '', text)     ## Quitamos puntuaciones
    text = re.sub(r'\s+', ' ', text)        ## Quitamos espacios extra

    return text.strip()

llamadas_cluster3["clean_text"] = llamadas_cluster3["transcription"].apply(clean_text)

llamadas_cluster3.head()

## Ya que dentro de las transcripciones hay palabras comunes que no nos aportan significado, creamos el array para poder omitirlas en el analisis

import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
stop_words = stopwords.words('spanish')

## Realizamos la vectorización del texto
from sklearn.feature_extraction.text import CountVectorizer

vector = CountVectorizer(stop_words=stop_words) ##Omitimos los stop_words en el conteo

resultado = vector.fit_transform(llamadas_cluster3["clean_text"])

palabras = vector.get_feature_names_out()
frecuencia = resultado.sum(axis=0).A1

## Creamos la tabla de frecuencias de palabras

frecuencias_df = pd.DataFrame({
    "word": palabras,
    "frequency": frecuencia
}).sort_values(by="frequency", ascending=False)

frecuencias_df.head(20)

## Siguen existiendo palabras propias del contexto del call center, por lo que ampliamos los stop_words:
stop_words_add = [
"cliente","client","agent","agente","nombre","momento","favor","gracias","si","sí","pues","entonces","usted","ustedes",
"aqui","aquí","numero","número","telefono","teléfono", "dia","día","dias","días", "sra", "hacer", "caso", "bien", "va",
"voy", "sé", "puedo", "ver", "dos", "claro", "ahí", "así", "bueno", "tal", "documento", "digo", "hoy", "dice", "puede", "listo",
"validacion", "verdad", "vamos", "mismo", "direccion", "ahorita", "direccion", "acá"]
stop_words = stop_words + stop_words_add

## Realizamos nuevamente el proceso de vectorización y creación de tabla de frecuencias:

vector = CountVectorizer(stop_words=stop_words)
resultado = vector.fit_transform(llamadas_cluster3["clean_text"])
palabras = vector.get_feature_names_out()
frecuencia = resultado.sum(axis=0).A1

frecuencias_df = pd.DataFrame({
    "word": palabras,
    "frequency": frecuencia
}).sort_values(by="frequency", ascending=False)

frecuencias_df.head(20)

rep_palabras = frecuencias_df.head(15)

plt.figure(figsize=(10,6))

sns.barplot(
    data=rep_palabras,
    x="frequency",
    y="word"
)

plt.title("Palabras más frecuentes en llamadas de cancelación")

plt.show()

## Vemos visualmente la frecuencia de palabras encontradas.

from wordcloud import WordCloud

texto = " ".join(llamadas_cluster3["clean_text"])

wordcloud = WordCloud(
    width=900,
    height=500,
    background_color="white",
    stopwords=stop_words
).generate(texto)

plt.figure(figsize=(12,6))
plt.imshow(wordcloud, interpolation="bilinear")
plt.axis("off")
plt.title("Nube palabras – Lllamadas Intencion (Cluster 3)")
plt.show()

"""Realizamos una agrupación, que nos pueda ayudar a identificar los principales temas por los que se puede presentar el churn

* Las palabras factura, valor ,tarifa, pagar, cuenta, mes, podría clasificarse en la razón: problemas con facturación o cobros
* Las palabras cancelar, cancelar, proceso, podría clasificarse en la razón:
clientes solicitando directamente cancelar el servicio
* Las palabras internet, servicio, servicios, linea podría clasificarse en la razón: problemas relacionados con el servicio y calidad del mismo

## **Relación EDA - NLP**

De lo encontrado en el analisis exploratorio y el NLP a las llamadas, podemos concluir:

| Motivo | Evidencia |
| :--- | :---: |
| Problemas de facturación | palabras: factura, tarifa, pagar, valor |
| Experiencia del cliente | 37.8% con reclamos |
| Problemas técnicos | downtime + palabras internet / servicio |

## **Diseño de Estrategias**

Para atacar el motivo 1: **Problemas de Facturación**, se podría:

***Estrategia reactiva***
* Implementar un protocolo de resolución prioritaria para reclamos relacionados con facturación, que incluya una revisión, correción y compensación de cargos en la factura.

***Estrategia Proactiva***

* Implementar un sistema de alertas preventivas de facturación. Donde se le notifique al cliente antes de cambios en la tarifa tarifa y se realicen llamadas explicando cambios o realizando comparativo con facturas anteriores.

Para atacar el motivo 2: **Problemas de Experiencia del cliente**, se podría:

***Estrategia reactiva***
* Implementar un sistema de gestión prioritario de reclamos para clientes del cluster crítico, incluyendo atención prioritaria en call center y resolución acelerada de incidencias.

***Estrategia Proactiva***
* Implementar un sistema de alertas preventivas de reclamación, monitoreando clientes con alta frecuencia de reclamos. También un programa de llamadas proactivas con algún tipo de compensación o seguimiento prioritario.

Para atacar el motivo 3: **Problemas técnicos**, se podría:

***Estrategia reactiva***
* Crear un protocolo de atención prioritaria para fallas técnicas en clientes del cluster crítico: Asignación prioritario de visitas técnicas, escalamiento automatico de casos de alto downtime.

***Estrategia Proactiva***
* Implementar un sistema de monitorio preventivo de red, identificando nodos con alta incidencia y realizando mantenimientos preventivos para poder hacer una intervención antes del reclamo.

Adicional, para atacar los 3 motivos, también se puede implementar Bundles de contenido streaming para clientes con intención de cancelación, ya que como observamos en el EDA, hay espacio para estrategias de fidelización usando plataformas streaming.

## **Métricas de Impacto**

En el EDA se identificaron:
- 19.5% de los clientes presentan intención de cancelación (1 de cada 5 clientes). Se estimaría una reducción de un 5%
- 37.8% de los clientes presentan al menos un reclamo mensual (4 de cada 10). Según búsquedas, un programa normal de recovery podría lograr una reducción del 10%
- 12.1% de los clientes experimentan interrupciones del servicio (1 de cada 8). Según busquedas, los mantenimientos preventivos podrían llegar a realizar una disminución de al menos 5%

Con base en estos indicadores, se proponen los siguientes objetivos de mejora para evaluar el impacto de las iniciativas estratégicas:

| Métrica | Valor actual | Objetivo |
|------|------|------|
Intención de cancelación | 19.5% | 14–16% |
Clientes con reclamos | 37.8% | <34% |
Clientes con downtime | 12.1% | <10% |
"""

